---
abstract: 'a portable interface to open and send raw data to network'
author:
  - 'GomoR <gomor-cpan_at_gomor.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Write
no_index:
  directory:
    - t
    - inc
requires:
  Class::Gomor: 0
  Net::Pcap: 0.12
  Socket6: 0
version: 1.07
