--- #YAML:1.0
name:                Net-Write
version:             1.04
abstract:            a portable interface to open and send raw data to network
license:             artistic
author:              
    - GomoR <perl@gomor.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Class::Gomor:                  0
    Net::Pcap:                     0.12
    Socket6:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
