# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Write
version:      0.82
version_from: lib/Net/Write.pm
installdirs:  site
requires:
    Class::Gomor:                  0
    Net::Pcap:                     0.12
    Socket6:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
